language: cpp
matrix:
  include:
  - env: QT=qt5osx
    os: osx
    osx_image: xcode9.3
  - env: QT=qt4
    os: linux
  - env: QT=qt5
    os: linux
  - env: QT=qt5NoPoppler
    os: linux
  - env: QT=qt5Release
    os: linux
  - env: QT=qt5win
    os: linux
dist: trusty
sudo: required
branches:
  only:
  - master
  - "/^\\d+.\\d+(.\\d+)?(\\S*)?$/"
before_install:
- "${TRAVIS_BUILD_DIR}/travis-ci/get-dependencies.sh"
before_script:
- export DISPLAY=:99.0
- "${TRAVIS_BUILD_DIR}/travis-ci/configure.sh"
script:
- if [ $QT = qt5win ]; then PATH=$PATH:/usr/lib/mxe/usr/bin; fi
- make -j 2
- export QT_QPA_PLATFORM=minimal
- if [ $QT = qt5 ]; then ./texstudio --auto-tests; fi
after_success:
- "${TRAVIS_BUILD_DIR}/travis-ci/package.sh"
deploy: 
  - provider: bintray
    skip_cleanup: true
    file: ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    user: sunderme
    on:
      condition: -f ${TRAVIS_BUILD_DIR}/travis-ci/bintray.json
    key:
       secure: "bLbz35zmzsOwnFX0mz55YKEYDZWBApGhrEqWRk8V0ZS6rkMjqjdbEz8mL6W3GNkJ4YIhrFJyMkWKUyBfc+kWJGAJdmHb8x8W1ZJ2xdXGWcPfEAYwwOAcVwWs2IM3reCg2jxrRrqDZOKo+f2Ie8YnnR2CLHRdUFzO6d0LOhctuAwGkNZVvM5uuW7EBBSuIeotatPV53I74hKodKUHC1t4jH+fm4/+AXgkPv4FpXPHrGaba6sb4fnLqSH4Vd/hEPlT9CJlnjmrr1on311c08f65iHIuAJAyFtsHi7x6tjuycBzV78Jok3EyNntALuqhrY3lQSnxNZumqGsUreuTquMc6+3VmE1c8UTFMWnOzP1q0AhydxcVKRWMNmvF58rGYkcHNMwhNojSxOGNj6JMNWbfm487KqKDtsR3XrI2qEgRAa3SqC/BV/XcZBBGgTmG7BdAl4Fl0gp8THMa+J5ee7aILCEoyC54VDD1BuBid4SEFKKvBjq2Rv43/QOHyogE5ew/S6jxx1OSWqjCBdismF7TSsK0kuf0NDf4y/6petceYhIjOs87S+WsCvSkl6SRnZUmr6GSTH/C80/uSGPy2TX4Pc2bCuVLKckrrQPjdeHgY0/xATVvloZOkWGHSXJ+4NXwKyxEdRViW4Df0lAtePtK8OpWok4LmBmmN8nQkfBVPU="
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: DQEuiEzNzXF9EhGLmMN/SrDjinVJbMgdmEZtokY9ZPp+yLqTHcvdX4EfuzbVElz14dAOK2H4TBK2q+13ZjCzuvWdgbdb72M4lNOk7YcHmpxK4XuvhYxsY02QxO0zTHCqWhZGL87jrTlBWICEZCuvXAg7/FHry0HqSsukUmP6cCVeIB8q33+8GwOVPUjXF9kRf9UgogtFhIcS0TwwGezdngkhonxBJYgaEYgZRxMPts1Fb+7ifmtjbZwF2QUUYZQvp0dFeI8S0w0lQKP+gVxNY8CAYKnIJ/STFJA6tXCstpKL2EPjbOhgI34DYBTCg4+peFOOLbVpBlwhInOeaYF35VryjulpMsNM9LdJH9gXiSOHOr4vxnr2M4ijLssd+p2dCZ1oeG9kHfARupmtmKer8lbrPkHrD1QGiwEOnrIZqV0TrJvnXTlJDtbOJnB+43lCzsIHJ4WDTpREHq8p2XoVBljlcVac3Kl6MmY5LVNtbdwBxirWF8hheEh/K4Cxv9wzktsP20/M3wpk2VFf2qL9ZxjugtxoT92WRVuHtCvLN8Zp+ekHZuhik5ImJXvVOavCy76SpBbJhz1sSnbjM2pFy9F9dHzYkMAVEX2i1iHQJKSVl82YpaqW0QTUAdRcyRLL4KVQOYAPJp8Ne9kkRc/rhX1aVOY3kp1GzInAEAJ89vA=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.dmg"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.dmg"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: DQEuiEzNzXF9EhGLmMN/SrDjinVJbMgdmEZtokY9ZPp+yLqTHcvdX4EfuzbVElz14dAOK2H4TBK2q+13ZjCzuvWdgbdb72M4lNOk7YcHmpxK4XuvhYxsY02QxO0zTHCqWhZGL87jrTlBWICEZCuvXAg7/FHry0HqSsukUmP6cCVeIB8q33+8GwOVPUjXF9kRf9UgogtFhIcS0TwwGezdngkhonxBJYgaEYgZRxMPts1Fb+7ifmtjbZwF2QUUYZQvp0dFeI8S0w0lQKP+gVxNY8CAYKnIJ/STFJA6tXCstpKL2EPjbOhgI34DYBTCg4+peFOOLbVpBlwhInOeaYF35VryjulpMsNM9LdJH9gXiSOHOr4vxnr2M4ijLssd+p2dCZ1oeG9kHfARupmtmKer8lbrPkHrD1QGiwEOnrIZqV0TrJvnXTlJDtbOJnB+43lCzsIHJ4WDTpREHq8p2XoVBljlcVac3Kl6MmY5LVNtbdwBxirWF8hheEh/K4Cxv9wzktsP20/M3wpk2VFf2qL9ZxjugtxoT92WRVuHtCvLN8Zp+ekHZuhik5ImJXvVOavCy76SpBbJhz1sSnbjM2pFy9F9dHzYkMAVEX2i1iHQJKSVl82YpaqW0QTUAdRcyRLL4KVQOYAPJp8Ne9kkRc/rhX1aVOY3kp1GzInAEAJ89vA=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-portable-qt5.zip"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-portable-qt5.zip"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: DQEuiEzNzXF9EhGLmMN/SrDjinVJbMgdmEZtokY9ZPp+yLqTHcvdX4EfuzbVElz14dAOK2H4TBK2q+13ZjCzuvWdgbdb72M4lNOk7YcHmpxK4XuvhYxsY02QxO0zTHCqWhZGL87jrTlBWICEZCuvXAg7/FHry0HqSsukUmP6cCVeIB8q33+8GwOVPUjXF9kRf9UgogtFhIcS0TwwGezdngkhonxBJYgaEYgZRxMPts1Fb+7ifmtjbZwF2QUUYZQvp0dFeI8S0w0lQKP+gVxNY8CAYKnIJ/STFJA6tXCstpKL2EPjbOhgI34DYBTCg4+peFOOLbVpBlwhInOeaYF35VryjulpMsNM9LdJH9gXiSOHOr4vxnr2M4ijLssd+p2dCZ1oeG9kHfARupmtmKer8lbrPkHrD1QGiwEOnrIZqV0TrJvnXTlJDtbOJnB+43lCzsIHJ4WDTpREHq8p2XoVBljlcVac3Kl6MmY5LVNtbdwBxirWF8hheEh/K4Cxv9wzktsP20/M3wpk2VFf2qL9ZxjugtxoT92WRVuHtCvLN8Zp+ekHZuhik5ImJXvVOavCy76SpBbJhz1sSnbjM2pFy9F9dHzYkMAVEX2i1iHQJKSVl82YpaqW0QTUAdRcyRLL4KVQOYAPJp8Ne9kkRc/rhX1aVOY3kp1GzInAEAJ89vA=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-qt5.exe"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-qt5.exe"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: DQEuiEzNzXF9EhGLmMN/SrDjinVJbMgdmEZtokY9ZPp+yLqTHcvdX4EfuzbVElz14dAOK2H4TBK2q+13ZjCzuvWdgbdb72M4lNOk7YcHmpxK4XuvhYxsY02QxO0zTHCqWhZGL87jrTlBWICEZCuvXAg7/FHry0HqSsukUmP6cCVeIB8q33+8GwOVPUjXF9kRf9UgogtFhIcS0TwwGezdngkhonxBJYgaEYgZRxMPts1Fb+7ifmtjbZwF2QUUYZQvp0dFeI8S0w0lQKP+gVxNY8CAYKnIJ/STFJA6tXCstpKL2EPjbOhgI34DYBTCg4+peFOOLbVpBlwhInOeaYF35VryjulpMsNM9LdJH9gXiSOHOr4vxnr2M4ijLssd+p2dCZ1oeG9kHfARupmtmKer8lbrPkHrD1QGiwEOnrIZqV0TrJvnXTlJDtbOJnB+43lCzsIHJ4WDTpREHq8p2XoVBljlcVac3Kl6MmY5LVNtbdwBxirWF8hheEh/K4Cxv9wzktsP20/M3wpk2VFf2qL9ZxjugtxoT92WRVuHtCvLN8Zp+ekHZuhik5ImJXvVOavCy76SpBbJhz1sSnbjM2pFy9F9dHzYkMAVEX2i1iHQJKSVl82YpaqW0QTUAdRcyRLL4KVQOYAPJp8Ne9kkRc/rhX1aVOY3kp1GzInAEAJ89vA=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-x86_64.AppImage"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-x86_64.AppImage"

