name: CI
on:
  - push
  - pull_request

jobs:
  build-linux:
    name: Linux-autoTests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Updates
      run: sudo apt-get update

    - name: Dependencies

      run: sudo apt-get install qtbase5-dev qt5-default qt5-qmake libqt5svg5-dev libqt5qml5-dev qttools5-dev libqt5svg5-dev zlib1g-dev pkg-config

    - name: Configure
      run: qmake texstudio.pro CONFIG+=debug NO_POPPLER_PREVIEW=1


    - name: Build
      run: make -j 2

    - name: Test
      run: QT_QPA_PLATFORM=offscreen ./texstudio --auto-tests


